#cloud-config
package_update: true

bootcmd:
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - netplan apply
