#cloud-config
package_update: true

write_files:
  - path: /var/run/have_not_yet_rebooted
    content: "cloud-init is running"
    permissions: "0644"

bootcmd:
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - >
    ACTUAL_IF=$(ip route show default | awk '{print $5}' | head -1) &&
    sed -i "s/eth0/$ACTUAL_IF/g" /etc/netplan/50-cloud-init.yaml &&
    sed -i '/match:/,+1d' /etc/netplan/50-cloud-init.yaml &&
    sed -i '/set-name:/d' /etc/netplan/50-cloud-init.yaml &&
    netplan apply

power_state:
  mode: reboot
  delay: 1
  condition: "test -f /var/lib/cloud/instance/boot-finished"
