#!/usr/bin/env python3
"""Generate SCHEMA_REFERENCE.md from infrastructure.schema.yaml.

Flattens the JSON Schema's nested properties (with path prefixes like
clusters[].name) into a single markdown table per section, so the schema
docs never drift from the schema itself. Regenerate with `viinfra --regen`.
"""

import sys
import yaml


def collect_properties(schema_node, path_prefix=""):
    """Recursively collect properties with metadata."""
    props = []

    if "properties" in schema_node:
        for name, node in schema_node["properties"].items():
            full_path = f"{path_prefix}.{name}" if path_prefix else name
            props.append({
                "path": full_path,
                "name": name,
                "type": node.get("type", "any"),
                "default": node.get("default"),
                "description": node.get("description", ""),
                "pattern": node.get("pattern"),
                "enum": node.get("enum"),
                "minimum": node.get("minimum"),
                "maximum": node.get("maximum"),
                "minLength": node.get("minLength"),
                "format": node.get("format"),
            })
            if node.get("type") == "object":
                if "properties" in node:
                    props.extend(collect_properties(node, full_path))
                elif "patternProperties" in node:
                    props.extend(collect_properties(node, full_path))
            elif node.get("type") == "array" and "items" in node:
                items = node["items"]
                if items.get("type") == "object":
                    if "properties" in items:
                        props.extend(collect_properties(items, f"{full_path}[]"))
                    elif "patternProperties" in items:
                        props.extend(collect_properties(items, f"{full_path}[]"))

    if "patternProperties" in schema_node:
        for pattern, node in schema_node["patternProperties"].items():
            full_path = f"{path_prefix}.*" if path_prefix else "*"
            props.append({
                "path": full_path,
                "name": pattern,
                "type": node.get("type", "any"),
                "default": node.get("default"),
                "description": node.get("description", ""),
                "pattern": None,
                "enum": node.get("enum"),
                "minimum": node.get("minimum"),
                "maximum": node.get("maximum"),
                "minLength": None,
                "format": None,
            })
            if node.get("type") == "object" and "properties" in node:
                props.extend(collect_properties(node, full_path))
            elif node.get("type") == "array" and "items" in node:
                items = node["items"]
                if items.get("type") == "object" and "properties" in items:
                    props.extend(collect_properties(items, f"{full_path}[]"))

    return props


def calc_level(path):
    """Calculate YAML indentation depth from path.

    Each dot (or [] for arrays) is one nesting level, which drives the
    indentation shown next to each property path in the reference doc.
    """
    return path.count(".") + path.count("[]")


def format_constraints(prop):
    """Format constraints string for a property."""
    parts = []

    if prop.get("pattern"):
        parts.append(f"pattern: {prop['pattern']}")
    if prop.get("enum"):
        vals = ", ".join(str(v) for v in prop["enum"])
        parts.append(f"values: {vals}")
    if prop.get("minimum") is not None:
        parts.append(f"min: {prop['minimum']}")
    if prop.get("maximum") is not None:
        parts.append(f"max: {prop['maximum']}")
    if prop.get("minLength") is not None:
        parts.append(f"minLength: {prop['minLength']}")
    if prop.get("format"):
        parts.append(f"format: {prop['format']}")

    return "; ".join(parts) if parts else None


def generate_markdown(schema):
    """Generate markdown reference document from schema."""
    lines = []

    lines.append("# Infrastructure Schema Reference")
    lines.append("")
    lines.append("<!-- Generated by scripts/generate-schema-docs.py -- do not edit manually -->")
    lines.append("")
    lines.append(f"> {schema.get('description', '')}")
    lines.append("")

    # Top-level required fields
    required = schema.get("required", [])
    if required:
        lines.append("## Required Fields")
        lines.append("")
        for field in required:
            desc = schema["properties"].get(field, {}).get("description", "")
            lines.append(f"- **`{field}`** — {desc}")
        lines.append("")

    # Sections for each top-level property
    for prop_name, prop_node in schema.get("properties", {}).items():
        section_title = prop_name.replace("_", " ").title()
        lines.append(f"## {section_title}")
        lines.append("")

        desc = prop_node.get("description", "")
        ptype = prop_node.get("type", "any")
        default = prop_node.get("default")

        if desc:
            lines.append(f"{desc}")
            lines.append("")

        if ptype == "object" and ("properties" in prop_node or "patternProperties" in prop_node):
            props = collect_properties(prop_node, prop_name)
            if props:
                # Table header
                lines.append("| Property | Type | Default | Constraints | Description |")
                lines.append("|---|---|---|---|---|")
                for p in props:
                    path = p["path"]
                    level = calc_level(path)
                    ptype_str = p["type"]
                    default_str = f"`{p['default']}`" if p["default"] is not None else "—"
                    constraints = format_constraints(p)
                    constraints_str = f"`{constraints}`" if constraints else "—"
                    desc_str = p["description"] or "—"
                    lines.append(f"| `{path} ({level})` | {ptype_str} | {default_str} | {constraints_str} | {desc_str} |")
                lines.append("")
        elif ptype == "array":
            lines.append(f"Type: `array`")
            lines.append("")
            items = prop_node.get("items", {})
            if items.get("type") == "object" and "properties" in items:
                props = collect_properties(items, f"{prop_name}[]")
                if props:
                    lines.append("| Property | Type | Default | Constraints | Description |")
                    lines.append("|---|---|---|---|---|")
                    for p in props:
                        path = p["path"]
                        level = calc_level(path)
                        ptype_str = p["type"]
                        default_str = f"`{p['default']}`" if p["default"] is not None else "—"
                        constraints = format_constraints(p)
                        constraints_str = f"`{constraints}`" if constraints else "—"
                        desc_str = p["description"] or "—"
                        lines.append(f"| `{path} ({level})` | {ptype_str} | {default_str} | {constraints_str} | {desc_str} |")
                    lines.append("")
        else:
            # Simple type
            parts = [f"Type: `{ptype}`"]
            if default is not None:
                parts.append(f"Default: `{default}`")
            constraints = format_constraints(prop_node)
            if constraints:
                parts.append(f"Constraints: `{constraints}`")
            lines.append(". ".join(parts) + ".")
            lines.append("")

    return "\n".join(lines)


def main():
    schema_path = "conf/infrastructure.schema.yaml"
    output_path = "docs/SCHEMA_REFERENCE.md"

    with open(schema_path) as f:
        schema = yaml.safe_load(f)

    md = generate_markdown(schema)

    with open(output_path, "w") as f:
        f.write(md + "\n")

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
